#ifndef F738FE90_52E0_4F82_9BB5_5833C5E4D2CB
#define F738FE90_52E0_4F82_9BB5_5833C5E4D2CB

enum TokenType {
    // Fin de flux (Obligatoire)
    TOKEN_EOF,

    // Littéraux la valeur directe "string", 123, 12.34, true/false
    TOKEN_LIT_INT, 
    TOKEN_LIT_FLOAT,
    TOKEN_LIT_CHAINE,
    TOKEN_LIT_BOLEEN,

    TOKEN_IDENTIFIANT,  

    TOKEN_PLUS,         
    TOKEN_MOINS,        
    TOKEN_ETOILE,       
    TOKEN_SLASH,
    TOKEN_MODULO,
    TOKEN_PLUS_PETIT,
    TOKEN_PLUS_GRAND,
    TOKEN_PLUS_PETIT_EGAL,
    TOKEN_PLUS_GRAND_EGAL,      

    TOKEN_EGAL,         
    TOKEN_EGAL_EGAL,
    TOKEN_DIFFERENT,    

    // Structure
    TOKEN_PAREN_OUVERTE,
    TOKEN_PAREN_FERMEE,
    TOKEN_ACCOLADE_OUVERTE,
    TOKEN_ACCOLADE_FERMEE,
    TOKEN_CROCHET_OUVERT,
    TOKEN_CROCHET_FERME,
    TOKEN_POINT_VIRGULE,
    TOKEN_VIRGULE,      
    
    // Mots-clés (Mieux vaut être spécifique)
    TOKEN_FONCTION,    
    TOKEN_SI,          
    TOKEN_SINON,       
    TOKEN_TANT_QUE,
    TOKEN_POUR,
    TOKEN_RETOUR,
    TOKEN_VRAI,
    TOKEN_FAUX,
    TOKEN_PRINT,
    TOKEN_MAIN,

    // variable 

    TOKEN_AFF, 
    TOKEN_DEC,
    TOKEN_TYPE_INT,
    TOKEN_TYPE_FLOAT,
    TOKEN_TYPE_STRING,
    TOKEN_TYPE_BOOL, 
    TOKEN_TYPE_VOID,
};


#endif /* F738FE90_52E0_4F82_9BB5_5833C5E4D2CB */
