#include "compiler/visitor/ast_graph_viz/general_visitor_graph_viz.h"
#include "compiler/visual_graph/output_visual_graph_text.h"
#include "compiler/visitor/visitor_base_generale.h"
#include "compiler/ast/ast_genere_copy.txt"
#include "compiler/ast/ast_genere_copy.txt"

#if 1
// Do not modify the code; this section is dynamically generated by the Jinja2 template.
GeneralVisitorGraphViz::GeneralVisitorGraphViz(OutputVisualGraphText outputVisualGraph)
    : _outputVisualGraph(std::move(outputVisualGraph))
{}

GeneralVisitorGraphViz::~GeneralVisitorGraphViz()
{}

void GeneralVisitorGraphViz::generate()
{
    _outputVisualGraph.generate();
}

void GeneralVisitorGraphViz::visiter(NodeInstruction* node)
{
    // (void)node;
    // int idNode = _outputVisualGraph.addNode("Instruction");
    // for (auto* element : node->getChildren())
    // {
    //     element->accept(this);
    //     int idChild = _pileIds.top();
    //     _pileIds.pop();
    //     _outputVisualGraph.addEdge(idNode, idChild);
    // }
    // _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeCallFunction* node)
{
    // (void)node;
    //  int idNode = _outputVisualGraph.addNode(node->getNomFunction().value.str());
    //  for (auto* element : node->getChildren())
    //  {
    //      element->accept(this);
    //      int idChild = _pileIds.top();
    //      _pileIds.pop();
    //      _outputVisualGraph.addEdge(idNode, idChild);
    //  }
    //  _pileIds.push(idNode);  // À CHANGER, C'eST JUSTE POUR TESTER SI CA COMPILE
}
void GeneralVisitorGraphViz::visiter(NodeArgFunction* node)
{
    // (void)node;
    // int idNode = _outputVisualGraph.addNode(node->getNom().value.str());
    // _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeDeclarationFunction* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode(node->getVisibilite().value.str());
    for (auto* element : node->getArguments())
    {
        element->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    if (node->getBody() != nullptr)
    {
        node->getBody()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeReturn* node)
{
    // (void)node;
    // int idNode = _outputVisualGraph.addNode("Return");
    // if (node->getValeurReturn() != nullptr)
    // {
    //     node->getValeurReturn()->accept(this);
    //     int idChild = _pileIds.top();
    //     _pileIds.pop();
    //     _outputVisualGraph.addEdge(idNode, idChild);
    // }
    // _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeAssignmentVariable* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode(node->getNom().value.str());
    if (node->getExpression() != nullptr)
    {
        node->getExpression()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeDeclarationVariable* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode(node->getVisibilite().value.str());
    if (node->getExpression() != nullptr)
    {
        node->getExpression()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeRefVariable* node)
{
    // (void)node;
    // int idNode = _outputVisualGraph.addNode(node->getNomVariable().value.str());
    // _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeUnRefVariable* node)
{
    // (void)node;
    // int idNode = _outputVisualGraph.addNode(node->getNomVariable().value.str());
    // _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeIdentifiant* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode("Identifiant");
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeAssignmentArray* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode(node->getNom().value.str());
    if (node->getExpressionIndex() != nullptr)
    {
        node->getExpressionIndex()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    if (node->getExpression() != nullptr)
    {
        node->getExpression()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeArrayInitialization* node)
{
    // (void)node;
    // int idNode = _outputVisualGraph.addNode("ArrayInitialization");
    // for (auto* element : node->getElements())
    // {
    //     element->accept(this);
    //     int idChild = _pileIds.top();
    //     _pileIds.pop();
    //     _outputVisualGraph.addEdge(idNode, idChild);
    // }
    // _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeReadingArray* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode(node->getNomArray().value.str());
    if (node->getIndexEquation() != nullptr)
    {
        node->getIndexEquation()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeClass* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode(node->getNomClass().value.str());
    for (auto* element : node->getHeritage())
    {
        element->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    for (auto* element : node->getListMembers())
    {
        element->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    for (auto* element : node->getBuilder())
    {
        element->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeCallObject* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode(node->getNomObject().value.str());
    for (auto* element : node->getChildren())
    {
        element->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeAccesAttribute* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode(node->getNomObject().value.str());
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeDeclarationObject* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode(node->getNomObject().value.str());
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeIf* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode("If");
    if (node->getNodeCondition() != nullptr)
    {
        node->getNodeCondition()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    if (node->getNodeBlocIf() != nullptr)
    {
        node->getNodeBlocIf()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    if (node->getNodeBlocElse() != nullptr)
    {
        node->getNodeBlocElse()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    if (node->getNodeBlocEndif() != nullptr)
    {
        node->getNodeBlocEndif()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeNew* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode(node->getNomType().value.str());
    for (auto* element : node->getArguments())
    {
        element->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeDelete* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode(node->getNomType().value.str());
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeInclude* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode(node->getPath().value.str());
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeWhile* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode("While");
    if (node->getNodeCondition() != nullptr)
    {
        node->getNodeCondition()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    if (node->getNodeBlocWhile() != nullptr)
    {
        node->getNodeBlocWhile()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    if (node->getNodeBlocFinWhile() != nullptr)
    {
        node->getNodeBlocFinWhile()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeOperation* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode(node->getToken().value.str());
    if (node->getGauche() != nullptr)
    {
        node->getGauche()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    if (node->getDroite() != nullptr)
    {
        node->getDroite()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeLiteral* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode(node->getToken().value.str());
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeNegation* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode(node->getOperateur().value.str());
    if (node->getOperande() != nullptr)
    {
        node->getOperande()->accept(this);
        int idChild = _pileIds.top();
        _pileIds.pop();
        _outputVisualGraph.addEdge(idNode, idChild);
    }
    _pileIds.push(idNode);
}
void GeneralVisitorGraphViz::visiter(NodeString* node)
{
    (void)node;
    int idNode = _outputVisualGraph.addNode("String");
    _pileIds.push(idNode);
}
#endif