#include "compiler/visitor/visitor_base_generale.h"
#include "compiler/ast/registry/context_gen_code.h"
#include "compiler/ast/registry/node_component_registry.h"
#include "compiler/macros/prysma_maybe_unused.h"
#include "compiler/ast/ast_genere.h"


VisitorBaseGenerale::VisitorBaseGenerale(ContextGenCode* contextGenCode)
    : _contextGenCode(contextGenCode)
{}

// Do not modify the code; this section is dynamically generated by the Jinja2 template.
void VisitorBaseGenerale::visiter(NodeInstruction* nodeInstruction)
{    
    auto& nodeInstructionData = _contextGenCode->getNodeComponentRegistry()->get<NodeInstructionComponents>(
        nodeInstruction->getNodeId()
    );
    
    for (auto* element : nodeInstructionData.getChildren())
    {
        element->accept(this);
    }
}

void VisitorBaseGenerale::visiter(NodeCallFunction* nodeCallFunction)
{    
    auto& nodeCallFunctionData = _contextGenCode->getNodeComponentRegistry()->get<NodeCallFunctionComponents>(
        nodeCallFunction->getNodeId()
    );

    for (auto* element : nodeCallFunctionData.getChildren())
    {
        element->accept(this);
    }
}

void VisitorBaseGenerale::visiter(NodeArgFunction* nodeArgFunction PRYSMA_MAYBE_UNUSED)
{}

void VisitorBaseGenerale::visiter(NodeDeclarationFunction* nodeDeclarationFunction)
{    
    auto& nodeDeclarationFunctionData = _contextGenCode->getNodeComponentRegistry()->get<NodeDeclarationFunctionComponents>(
        nodeDeclarationFunction->getNodeId()
    );

    for (auto* element : nodeDeclarationFunctionData.getArguments())
    {
        element->accept(this);
    }    
    if (nodeDeclarationFunctionData.getBody() != nullptr)
    {
        nodeDeclarationFunctionData.getBody()->accept(this);
    }
}

void VisitorBaseGenerale::visiter(NodeReturn* nodeReturn)
{    
    auto& nodeReturnData = _contextGenCode->getNodeComponentRegistry()->get<NodeReturnComponents>(
        nodeReturn->getNodeId()
    );

    if (nodeReturnData.getReturnValue() != nullptr)
    {
        nodeReturnData.getReturnValue()->accept(this);
    }
}

void VisitorBaseGenerale::visiter(NodeAssignmentVariable* nodeAssignmentVariable)
{    
    auto& nodeAssignmentVariableData = _contextGenCode->getNodeComponentRegistry()->get<NodeAssignmentVariableComponents>(
        nodeAssignmentVariable->getNodeId()
    );

    if (nodeAssignmentVariableData.getExpression() != nullptr)
    {
        nodeAssignmentVariableData.getExpression()->accept(this);
    }
}

void VisitorBaseGenerale::visiter(NodeDeclarationVariable* nodeDeclarationVariable)
{    
    auto& nodeDeclarationVariableData = _contextGenCode->getNodeComponentRegistry()->get<NodeDeclarationVariableComponents>(
        nodeDeclarationVariable->getNodeId()
    );

    if (nodeDeclarationVariableData.getExpression() != nullptr)
    {
        nodeDeclarationVariableData.getExpression()->accept(this);
    }
}

void VisitorBaseGenerale::visiter(NodeRefVariable* nodeRefVariable PRYSMA_MAYBE_UNUSED)
{}

void VisitorBaseGenerale::visiter(NodeUnRefVariable* nodeUnRefVariable PRYSMA_MAYBE_UNUSED)
{}

void VisitorBaseGenerale::visiter(NodeIdentifiant* nodeIdentifiant PRYSMA_MAYBE_UNUSED)
{}

void VisitorBaseGenerale::visiter(NodeAssignmentArray* nodeAssignmentArray)
{    
    auto& nodeAssignmentArrayData = _contextGenCode->getNodeComponentRegistry()->get<NodeAssignmentArrayComponents>(
        nodeAssignmentArray->getNodeId()
    );

    if (nodeAssignmentArrayData.getExpressionIndex() != nullptr)
    {
        nodeAssignmentArrayData.getExpressionIndex()->accept(this);
    }    
    if (nodeAssignmentArrayData.getExpression() != nullptr)
    {
        nodeAssignmentArrayData.getExpression()->accept(this);
    }
}

void VisitorBaseGenerale::visiter(NodeArrayInitialization* nodeArrayInitialization)
{    
    auto& nodeArrayInitializationData = _contextGenCode->getNodeComponentRegistry()->get<NodeArrayInitializationComponents>(
        nodeArrayInitialization->getNodeId()
    );

    for (auto* element : nodeArrayInitializationData.getElements())
    {
        element->accept(this);
    }
}

void VisitorBaseGenerale::visiter(NodeReadingArray* nodeReadingArray)
{    
    auto& nodeReadingArrayData = _contextGenCode->getNodeComponentRegistry()->get<NodeReadingArrayComponents>(
        nodeReadingArray->getNodeId()
    );

    if (nodeReadingArrayData.getIndexEquation() != nullptr)
    {
        nodeReadingArrayData.getIndexEquation()->accept(this);
    }
}

void VisitorBaseGenerale::visiter(NodeClass* nodeClass)
{    
    auto& nodeClassData = _contextGenCode->getNodeComponentRegistry()->get<NodeClassComponents>(
        nodeClass->getNodeId()
    );

    for (auto* element : nodeClassData.getInheritance())
    {
        element->accept(this);
    }    
    for (auto* element : nodeClassData.getMembers())
    {
        element->accept(this);
    }  
    for (auto* element : nodeClassData.getBuilder())
    {
        element->accept(this);
    }
}

void VisitorBaseGenerale::visiter(NodeCallObject* nodeCallObject)
{    
    auto& nodeCallObjectData = _contextGenCode->getNodeComponentRegistry()->get<NodeCallObjectComponents>(
        nodeCallObject->getNodeId()
    );

    for (auto* element : nodeCallObjectData.getChildren())
    {
        element->accept(this);
    }
}

void VisitorBaseGenerale::visiter(NodeAccesAttribute* nodeAccesAttribute PRYSMA_MAYBE_UNUSED)
{}

void VisitorBaseGenerale::visiter(NodeDeclarationObject* nodeDeclarationObject PRYSMA_MAYBE_UNUSED)
{}

void VisitorBaseGenerale::visiter(NodeIf* nodeIf)
{    
    auto& nodeIfData = _contextGenCode->getNodeComponentRegistry()->get<NodeIfComponents>(
        nodeIf->getNodeId()
    );

    if (nodeIfData.getNodeCondition() != nullptr)
    {
        nodeIfData.getNodeCondition()->accept(this);
    }
    if (nodeIfData.getNodeBlocIf() != nullptr)
    {
        nodeIfData.getNodeBlocIf()->accept(this);
    }    
    if (nodeIfData.getNodeBlocElse() != nullptr)
    {
        nodeIfData.getNodeBlocElse()->accept(this);
    }    
    if (nodeIfData.getNodeBlocEndif() != nullptr)
    {
        nodeIfData.getNodeBlocEndif()->accept(this);
    }
}

void VisitorBaseGenerale::visiter(NodeNew* nodeNew)
{    
    auto& nodeNewData = _contextGenCode->getNodeComponentRegistry()->get<NodeNewComponents>(
        nodeNew->getNodeId()
    );

    for (auto* element : nodeNewData.getArguments())
    {
        element->accept(this);
    }
}

void VisitorBaseGenerale::visiter(NodeDelete* nodeDelete PRYSMA_MAYBE_UNUSED)
{}

void VisitorBaseGenerale::visiter(NodeInclude* nodeInclude PRYSMA_MAYBE_UNUSED)
{}

void VisitorBaseGenerale::visiter(NodeWhile* nodeWhile)
{    
    // auto& nodeWhileData = _contextGenCode->getNodeComponentRegistry()->get<NodeWhileComponents>( // en gros si je le réactive, ca explose
    //     nodeWhile->getNodeId()
    // );

    // if (nodeWhileData.getNodeCondition() != nullptr)
    // {
    //     nodeWhileData.getNodeCondition()->accept(this);
    // }    
    // if (nodeWhileData.getNodeWhileBlock() != nullptr)
    // {
    //     nodeWhileData.getNodeWhileBlock()->accept(this);
    // }    
    // if (nodeWhileData.getNodeWhileEndBlock() != nullptr)
    // {
    //     nodeWhileData.getNodeWhileEndBlock()->accept(this);
    // }
}

void VisitorBaseGenerale::visiter(NodeOperation* nodeOperation)
{    
    auto& nodeOperationData = _contextGenCode->getNodeComponentRegistry()->get<NodeOperationComponents>(
        nodeOperation->getNodeId()
    );

    if (nodeOperationData.getLeft() != nullptr)
    {
        nodeOperationData.getLeft()->accept(this);
    }    
    if (nodeOperationData.getRight() != nullptr)
    {
        nodeOperationData.getRight()->accept(this);
    }
}

void VisitorBaseGenerale::visiter(NodeLiteral* nodeLiteral PRYSMA_MAYBE_UNUSED)
{}

void VisitorBaseGenerale::visiter(NodeNegation* nodeNegation)
{    
    auto& nodeNegationData = _contextGenCode->getNodeComponentRegistry()->get<NodeNegationComponents>(
        nodeNegation->getNodeId()
    );

    if (nodeNegationData.getOperand() != nullptr)
    {
        nodeNegationData.getOperand()->accept(this);
    }
}

void VisitorBaseGenerale::visiter(NodeString* nodeString PRYSMA_MAYBE_UNUSED)
{}

