#include "compiler/visitor/visitor_base_generale.h"
#include "compiler/ast/ast_genere_copy.txt"

// Do not modify the code; this section is dynamically generated by the Jinja2 template.
void VisitorBaseGenerale::visiter(NodeInstruction* nodeInstruction)
{    
    // for (auto* element : nodeInstruction->getChildren())
    // {
    //     element->accept(this);
    // }
}

void VisitorBaseGenerale::visiter(NodeCallFunction* nodeCallFunction)
 { 
//    for (auto* element : nodeCallFunction->getChildren())
//     {
//         element->accept(this);
//     }
}

void VisitorBaseGenerale::visiter(NodeArgFunction* nodeArgFunction [[maybe_unused]])
{}

void VisitorBaseGenerale::visiter(NodeDeclarationFunction* nodeDeclarationFunction)
{    for (auto* element : nodeDeclarationFunction->getArguments())
    {
        element->accept(this);
    }    if (nodeDeclarationFunction->getBody() != nullptr)
    {
        nodeDeclarationFunction->getBody()->accept(this);
    }}

void VisitorBaseGenerale::visiter(NodeReturn* nodeReturn)
{    
    // if (nodeReturn->getValeurReturn() != nullptr)
    // {
    //     nodeReturn->getValeurReturn()->accept(this);
    // }
}

void VisitorBaseGenerale::visiter(NodeAssignmentVariable* nodeAssignmentVariable)
{    if (nodeAssignmentVariable->getExpression() != nullptr)
    {
        nodeAssignmentVariable->getExpression()->accept(this);
    }}

void VisitorBaseGenerale::visiter(NodeDeclarationVariable* nodeDeclarationVariable)
{    if (nodeDeclarationVariable->getExpression() != nullptr)
    {
        nodeDeclarationVariable->getExpression()->accept(this);
    }}

void VisitorBaseGenerale::visiter(NodeRefVariable* nodeRefVariable [[maybe_unused]])
{}

void VisitorBaseGenerale::visiter(NodeUnRefVariable* nodeUnRefVariable [[maybe_unused]])
{}

void VisitorBaseGenerale::visiter(NodeIdentifiant* nodeIdentifiant [[maybe_unused]])
{}

void VisitorBaseGenerale::visiter(NodeAssignmentArray* nodeAssignmentArray)
{    if (nodeAssignmentArray->getExpressionIndex() != nullptr)
    {
        nodeAssignmentArray->getExpressionIndex()->accept(this);
    }    if (nodeAssignmentArray->getExpression() != nullptr)
    {
        nodeAssignmentArray->getExpression()->accept(this);
    }}

void VisitorBaseGenerale::visiter(NodeArrayInitialization* nodeArrayInitialization)
{
    //     for (auto* element : nodeArrayInitialization->getElements())
    // {
    //     element->accept(this);
    // }
}

void VisitorBaseGenerale::visiter(NodeReadingArray* nodeReadingArray)
{    if (nodeReadingArray->getIndexEquation() != nullptr)
    {
        nodeReadingArray->getIndexEquation()->accept(this);
    }}

void VisitorBaseGenerale::visiter(NodeClass* nodeClass)
{    for (auto* element : nodeClass->getHeritage())
    {
        element->accept(this);
    }    for (auto* element : nodeClass->getListMembers())
    {
        element->accept(this);
    }    for (auto* element : nodeClass->getBuilder())
    {
        element->accept(this);
    }}

void VisitorBaseGenerale::visiter(NodeCallObject* nodeCallObject)
{    for (auto* element : nodeCallObject->getChildren())
    {
        element->accept(this);
    }}

void VisitorBaseGenerale::visiter(NodeAccesAttribute* nodeAccesAttribute [[maybe_unused]])
{}

void VisitorBaseGenerale::visiter(NodeDeclarationObject* nodeDeclarationObject [[maybe_unused]])
{}

void VisitorBaseGenerale::visiter(NodeIf* nodeIf)
{    if (nodeIf->getNodeCondition() != nullptr)
    {
        nodeIf->getNodeCondition()->accept(this);
    }    if (nodeIf->getNodeBlocIf() != nullptr)
    {
        nodeIf->getNodeBlocIf()->accept(this);
    }    if (nodeIf->getNodeBlocElse() != nullptr)
    {
        nodeIf->getNodeBlocElse()->accept(this);
    }    if (nodeIf->getNodeBlocEndif() != nullptr)
    {
        nodeIf->getNodeBlocEndif()->accept(this);
    }}

void VisitorBaseGenerale::visiter(NodeNew* nodeNew)
{    for (auto* element : nodeNew->getArguments())
    {
        element->accept(this);
    }}

void VisitorBaseGenerale::visiter(NodeDelete* nodeDelete [[maybe_unused]])
{}

void VisitorBaseGenerale::visiter(NodeInclude* nodeInclude [[maybe_unused]])
{}

void VisitorBaseGenerale::visiter(NodeWhile* nodeWhile)
{    if (nodeWhile->getNodeCondition() != nullptr)
    {
        nodeWhile->getNodeCondition()->accept(this);
    }    if (nodeWhile->getNodeBlocWhile() != nullptr)
    {
        nodeWhile->getNodeBlocWhile()->accept(this);
    }    if (nodeWhile->getNodeBlocFinWhile() != nullptr)
    {
        nodeWhile->getNodeBlocFinWhile()->accept(this);
    }}

void VisitorBaseGenerale::visiter(NodeOperation* nodeOperation)
{    if (nodeOperation->getGauche() != nullptr)
    {
        nodeOperation->getGauche()->accept(this);
    }    if (nodeOperation->getDroite() != nullptr)
    {
        nodeOperation->getDroite()->accept(this);
    }}

void VisitorBaseGenerale::visiter(NodeLiteral* nodeLiteral [[maybe_unused]])
{}

void VisitorBaseGenerale::visiter(NodeNegation* nodeNegation)
{    if (nodeNegation->getOperande() != nullptr)
    {
        nodeNegation->getOperande()->accept(this);
    }}

void VisitorBaseGenerale::visiter(NodeString* nodeString [[maybe_unused]])
{}

