#ifndef F738FE90_52E0_4F82_9BB5_5833C5E4D2CB
#define F738FE90_52E0_4F82_9BB5_5833C5E4D2CB

enum TokenType {
    // End of file
    TOKEN_EOF,

    // Literals: direct value "string", 123, 12.34, true/false
    TOKEN_LIT_INT, 
    TOKEN_LIT_FLOAT,
    TOKEN_LIT_STRING,
    TOKEN_LIT_BOOL,

    TOKEN_IDENTIFIER,  

    TOKEN_PLUS,         
    TOKEN_MINUS,        
    TOKEN_STAR,       
    TOKEN_SLASH,
    TOKEN_MODULO,
    TOKEN_LESS,
    TOKEN_GREATER,
    TOKEN_LESS_EQUAL,
    TOKEN_GREATER_EQUAL,      

    TOKEN_EQUAL,         
    TOKEN_EQUAL_EQUAL,
    TOKEN_NOT_EQUAL,
    TOKEN_AND,          
    TOKEN_OR,
    TOKEN_NOT,         

    // Structure
    TOKEN_PAREN_OPEN,
    TOKEN_PAREN_CLOSE,
    TOKEN_BRACE_OPEN,
    TOKEN_BRACE_CLOSE,
    TOKEN_BRACKET_OPEN,
    TOKEN_BRACKET_CLOSE,
    TOKEN_DOT,
    TOKEN_SEMICOLON,
    TOKEN_COLON,
    TOKEN_COMMA,      
    TOKEN_QUOTE,
    
    // Keywords 
    TOKEN_FUNCTION,    
    TOKEN_IF,          
    TOKEN_ELSE,       
    TOKEN_WHILE,
    TOKEN_FOR,
    TOKEN_RETURN,
    TOKEN_TRUE,
    TOKEN_FALSE,
    TOKEN_SCOPE,
    TOKEN_CALL,
    TOKEN_PASS,

    // variable 
    TOKEN_ARG,
    TOKEN_ASSIGN, 
    TOKEN_DECL,
    TOKEN_REF,
    TOKEN_UNREF,
    TOKEN_TYPE_INT,
    TOKEN_TYPE_FLOAT,
    TOKEN_TYPE_STRING,
    TOKEN_TYPE_BOOL, 
    TOKEN_TYPE_VOID,
    TOKEN_TYPE_CHAR,
    TOKEN_TYPE_INT64,
    TOKEN_TYPE_INT32,
    TOKEN_TYPE_PTR,
    TOKEN_CLASS,
    TOKEN_PUBLIC,
    TOKEN_PRIVATE,
    TOKEN_PROTECTED,

    // new
    TOKEN_NEW,
    TOKEN_DELETE,

    // include 
    TOKEN_INCLUDE
};

#endif /* F738FE90_52E0_4F82_9BB5_5833C5E4D2CB */
